services:
  mysql:
    image: mysql:8.1
    container_name: project-db
    ports:
      - "2706:3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 15s
      timeout: 15s
      retries: 3
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - network
  project-service:
    container_name: project-service
    hostname: project-service-1
    ports:
      - "80:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql:3306
      ROOT_LOG_LEVEL: error
      WEB_LOG_LEVEL: error
      EUREKA_APP_NAME: project-service
      PROFILE_ACTIVE: test
      EUREKA_IP_ADDR: 127.0.0.1
      EUREKA_PORT: 80
      REGISTER_ZONE: service-registry-1
      DEFAULT_ZONE: http://admin:admin@service-registry:80/eureka/
      SWAGGER_SERVER_URL: http://gateway:80
    env_file:
      - .env
    volumes:
      - logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
    networks:
      - network
volumes:
  logs:
    name: project-logs
  db-data:
    name: project-db
networks:
  network:
    name: project-network