services:
  mysql:
    image: mysql:8.1
    container_name: project-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
    volumes:
      - ./mysql/data:/var/lib/mysql