services:
  project-db:
    image: mysql:8.1
    container_name: project-db
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ./mysql-db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - project-network
  project-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-service
    ports:
      - "${SERVICE_PORT}:8080"
    environment:
      PROFILE_ACTIVE: dev
      DB_HOST: project-db:3306
      ROOT_LOG_LEVEL: error
      WEB_LOG_LEVEL: debug
    env_file:
      - .env
    volumes:
      - ./logs:/sc-project/logs
    depends_on:
      project-db:
        condition: service_healthy
        restart: true
    networks:
      - project-network
networks:
  project-network: