spring.application.name=project-service
spring.profiles.active=${PROFILE_ACTIVE:dev}

spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:mysql://${DB_HOST}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

springdoc.override-with-generic-response=false
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs

app.api-version=v1
app.api-docs-server=${SWAGGER_SERVER_URL}
app.file-service-url=${FILE_SERVICE_URL}
app.user-service-url=${USER_SERVICE_URL}